version: '3.7'

services:
  mysqldb:
    image: mysql
    mem_limit: 700m
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - "3307:3306"
    networks:
      - spring-network


  mysql-connect-docker-crud:
    image: tsbajaj/ms-mysql-connect-docker-crud:0.0.1-SNAPSHOT
    mem_limit: 700m
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "9090:8080"
    networks:
      - spring-network
    depends_on:
      - mysqldb


networks:
  spring-network:
    driver: bridge
